#################### Memo ####################
#先啟動docker container 再這個.yml 路徑下使用docker-compose
#指令
  #啟動且在背景執行
  #docker-compose up -d
  #關閉
  #docker-compose stop
  #刪除
  #docker-compose rm
  #關閉並刪除
  #docker-compose down

  #啟動 container terminal
  #docker exec -it <container_name> /bin/bash
  #單獨啟動 container
  #docker run -it redhat/ubi8
  #宿主機 copy 到 container
  #docker cp /Volumes/C/CentOS-Base.repo 1a42f6d61b44:/etc/yum.repos.d


#################### SingleAlone With Auth ####################
version: '3.5'
services:
  mongodb_single:
    image: mongo:6.0.6
    container_name: mongodb_single1
    ports:
      - "17010:17010"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod --auth --port 17010 --bind_ip_all


#################### Easy ReplicaSet Cluster ####################
#version: '3.5'
#services:
#  mongo1:
#    container_name: mongo11
#    image: mongo:6.0.6
#    ports:
#      - 17011:17011
#    command: mongod --port 17011 --bind_ip_all --replSet myReplicaSet
#  mongo2:
#    container_name: mongo12
#    image: mongo:6.0.6
#    ports:
#      - 17012:17012
#    command: mongod --port 17012 --bind_ip_all --replSet myReplicaSet
#  mongo3:
#    container_name: mongo13
#    image: mongo:6.0.6
#    ports:
#      - 17013:17013
#    command: mongod --port 17013 --bind_ip_all --replSet myReplicaSet