###################################################################
# 设置服务器端口
server:
  port: 8085


###################################################################
spring:
# JSP 配置
  #mvc:
  #  view:
  #    prefix: /WEB-INF/templates/
  #    suffix: .jsp
# thymeleaf 配置
  thymeleaf:
    cache: false # 禁用缓存，修改完实时展示数据
    prefix: /WEB-INF/templates/ # 文件所在位置
    suffix: .html # 后缀
  web:
    resources:
      static-locations: /WEB-INF/static/ # 静态资源

# 配置数据库连接
#MySQL
  datasource:
#    url: jdbc:mysql://localhost:3306
    username: root
    password: "!QAZ2wsx"

#MongoDB
  data:
    mongodb:
      database: employee
      authentication-database: admin
      # ver 2.4以後 (Template && Repository)
#      uri: mongodb://root:root:127.0.0.1:27017/employee
      uri: mongodb://localhost:27017/employee
      # ver 2.4前 (JDBC)
      host: 127.0.0.1
      port: 27017
      username: root
      password: root


###################################################################
# 日志设置
logging:
  level:
    root: INFO
    com.smart.mmogo: DEBUG
    org.springframework.data.mongodb.core: DEBUG


