# 设置服务器端口
server:
  port: 8084

# 配置数据库连接
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase
#    username: myusername
#    password: mypassword

# 日志设置
logging:
  level:
    root: INFO
    com.example.mypackage: DEBUG

# 自定义应用程序设置
#myapp:
#  customSetting1: value1
#  customSetting2: value2
