###################################################################
# 设置服务器端口
server:
  port: 8085


###################################################################
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 配置数据库连接
#MySQL
  datasource:
#    url: jdbc:mysql://localhost:3306
    username: root
    password: "!QAZ2wsx"

#MongoDB
  data:
    mongodb:
      database: employee
      authentication-database: admin
      # ver 2.4以後
#      uri: mongodb://root:root:127.0.0.1:27017
      # ver 2.4前
      host: 127.0.0.1
      port: 27017
      username: root
      password: root


###################################################################
# 日志设置
logging:
  level:
    root: INFO
    com.smart.mmogo: DEBUG
    org.springframework.data.mongodb.core: DEBUG


